export const formatCrm = (crm) => {
  return {
    id: crm.id,
    companyId: crm.empresa,
    personType: crm.tipop,
    fantasyName: crm.nome_fantasia,
    document: crm.cnpj_cpf,
    clientType: crm.tipo,
    socialReason: crm.razao_social,
    cnpjCpf: crm.cnpj_cpf,
    passport: crm.passaport,
    nacionality: crm.nacionalidade,
    citySubscription: crm.inscricao_municipal,
    stateSubscription: crm.inscricao_estadual,
    contact: crm.contato,
    email: crm.email,
    celphone: crm.telefone,
    cep: crm.cep,
    city: crm.cidade,
    neighborhood: crm.bairro,
    address: crm.endereco,
    number: crm.numero,
    addressComplement: crm.complemento,
    type: crm.tipo.toLowerCase(),
    status: crm.status,
    state: crm.estado,
    cf: crm.cf,
  };
};
